In [1]:
import numpy as np

In [2]:
A = np.array([[3,2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [4]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [7]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print(A_calc)

[[3. 2.]
 [4. 1.]]


Ejemplo 2 matriz simetrica real

In [8]:
B =  np.array([[3,2], [2,3]])
print(B)

[[3 2]
 [2 3]]


In [9]:
print(B == B.T)

[[ True  True]
 [ True  True]]


In [10]:
autovalores, autovectores = np.linalg.eig(B)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [12]:
# recordamos que para una matriz simetrica su inversa es igual a su traspuesta
# esto es computacionalmente mas economico que una inversa
B_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(B_calc)

[[3. 2.]
 [2. 3.]]


In [13]:
autovectores.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [14]:
np.linalg.inv(autovectores)

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])