In [1]:
import numpy as np

np.set_printoptions(suppress=True)

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


La peseudo inversa de Moore Penrose cuando verifica 4 condiciones existe y es unica

In [4]:
U,D,V = np.linalg.svd(A)

print('U')
print(U)

print("D")
print(D)

print("V")
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [6]:
D_pse = np.zeros((A.shape[0],A.shape[1])).T
D_pse 

array([[0., 0., 0.],
       [0., 0., 0.]])

Al calcular la pseudo inversa hacemos el inverso de cada elemento (1/d11, 1/d12 ...)

In [10]:
print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [12]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [14]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))

print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


Construirmos la pseudoinversa A

In [16]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Para validar esto calculemos la psudoinversa con numpy

In [18]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [19]:
print(A_pse == A_pse_calc)

[[ True  True  True]
 [False  True  True]]


In [20]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [21]:
print(A_pse_calc.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


Observamos que tenemos un -0, esto porque tenemos minimizados los valores cercanos a cero

In [22]:
np.set_printoptions(suppress=False)

In [23]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -1.77635684e-15]
 [ 4.44089210e-16  1.00000000e+00]]


- Observamos que la matriz no es exactamente la inversa, estamos teniendo algo muy cercano, ya que minimiza la norma 2 de estas distancias (de estos errores que estamos cometiendo).

- Otra propiedad es que estas matrices no son conmutativas

In [24]:
print(A.dot(A_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


Y cuando intentamos invertir las matrices obtenemos algo muy alejado de la identidad, tambien hay otras pseudoinversas, la mas usada es la de SVD la de Moore Penrose pero podemos escribir otra y obtener un valor igual o muy aproximado

In [27]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [31]:
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [32]:
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Si bien parecen iguales, la que esta calculada en python con SVD computacionalmente es mas certera, mas efectiva y tiene menos error.