In [47]:
import numpy as np

In [48]:
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [49]:
U, D, V = np.linalg.svd(A)

In [50]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [51]:
print(D)

[7.97638869 0.61418515]


In [52]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [53]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


**Contenido adicional solucion A = UDV**

UDV deben ser de dimensiones compatibles para realizar producto interno, asi que agregamos una columna con ceros al final

In [55]:
D_aumentada = np.hstack((np.diag(D),np.zeros((2,1))))
print(D_aumentada)

[[7.97638869 0.         0.        ]
 [0.         0.61418515 0.        ]]


In [62]:
A_calc = U.dot(D_aumentada).dot(V)
print(A_calc)

[[1. 2. 3.]
 [3. 4. 5.]]
